Resources/src/Entity/Sample/Post.php
<?php

namespace App\Entity\Sample;

use App\Repository\Sample\PostRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use http\Encoding\Stream;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Title;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Category;

    #[ORM\Column(type: 'text', nullable: true)]
    private $Content;

    #[ORM\Column(type: 'string', length: 1024, nullable: true)]
    private $Thumbnail;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Tag;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(?string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->Thumbnail;
    }

    public function setThumbnail(?string $Thumbnail): self
    {
        $this->Thumbnail = $Thumbnail;

        return $this;
    }

    public function getTag(): ?string
    {
        return $this->Tag;
    }

    public function setTag(?string $Tag): self
    {
        $this->Tag = $Tag;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(?string $Status): self
    {
        $this->Status = $Status;

        return $this;
    }
}

templates/base.html.twig
{% extends '@C3/_base.html.twig' %}

{% block page_icon %}{% if block("page_title") is defined %}far fa-user{% endif %}{% endblock %}

{% block app %}
{{ parent() }}
{% endblock %}

templates/menu.html.twig
{% set stock="" %}
          <ul class="sidebar-menu">
            {% for group in menu %}
            {% if stock != group.title %}
              <li class="menu-header">{{ group.title }}</li>
              {% set stock = group.title %}
            {% endif %}
            {% if group.item is defined %}
              {% for sub in group.item %}
                {% if sub.item is defined %}
                <li class="nav-item dropdown{{ ' active'|is_active(sub.item, page)|safe }}">
                  <a href="#" class="nav-link has-dropdown"><i class="{{ sub.icon|default('fas fa-square') }}"></i><span>{{ sub.title }}</span></a>
                  <ul class="dropdown-menu{{ ' show'|is_active(sub.item, page)|safe }}">
                    {% for item in sub.item %}
                      {% if item.url is defined %}{% set url = item.url %}
                      {% elseif item.path is defined %}{% set url = path(item.path) %}
                      {% else %}{% set url = app.request.baseUrl %}{% endif %}
                    <li{{ ' class=active'|is_active(url, page)|safe }}><a class="nav-link" href="{{ url }}">{{ item.title }}</a></li>
                    {% endfor %}
                  </ul>
                </li>
                {% else %}
                  {% if sub.url is defined %}{% set url = sub.url %}
                  {% elseif sub.path is defined %}{% set url = path(sub.path) %}
                  {% else %}{% set url = app.request.baseUrl %}{% endif %}
                  {% if sub.roles is not defined %}
                    <li{{ ' class="active"'|is_active('^blank(.*)', page)|safe }}><a class="nav-link" href="{{ url }}"><i class="{{ sub.icon|default('far fa-square') }}"></i> <span>{{ sub.title }}</span></a></li>
                  {% else %}
                    {% if sub.roles|slice(0,1)=="!" and not is_granted(sub.roles|slice(1)) %}
                      <li{{ ' class="active"'|is_active('^blank(.*)', page)|safe }}><a class="nav-link" href="{{ url }}"><i class="{{ sub.icon|default('far fa-square') }}"></i> <span>{{ sub.title }}</span></a></li>
                    {% elseif is_granted(sub.roles) %}
                      <li{{ ' class="active"'|is_active('^blank(.*)', page)|safe }}><a class="nav-link" href="{{ url }}"><i class="{{ sub.icon|default('far fa-square') }}"></i> <span>{{ sub.title }}</span></a></li>
                    {% endif %}
                  {% endif %}
                {% endif %}
              {% endfor %}
            {% else %}
              <li{{ ' class="active"'|is_active('^blank(.*)', page)|safe }}><a class="nav-link" href="{% if group.url is defined %}{{ group.url}}{% else %}{{ path(group.path|default(app.request.baseUrl)) }}{% endif %}"><i class="{{ group.icon|default('far fa-square') }}"></i> <span>{{ group.title }}</span></a></li>
            {% endif %}
            {% endfor %}
          </ul>

templates/menu_button.html.twig
{% set stock="" %}

    {% for group in menu %}
    <div class="card"><div class="card-body">
      {% if stock != group.title %}
        <h3 class="section-title card-title">{{ group.title }}</h3>
        {% set stock = group.title %}
      {% endif %}
      {% if group.item is defined %}
        <ul class="list-group  list-group-flush mb-3">
        {% for sub in group.item %}
          {% if sub.item is defined %}
          <li class="list-group-item">
            <div class="section-title"><i class="{{ sub.icon|default('fas fa-square') }}"></i> <span> {{ sub.title }}</span></div>
              {% for item in sub.item %}
                {% set url = item.url|default(path(item.path|default('app_home'))) %}
                <li class="list-group-item text-center"><a class="btn btn-primary btn-icon icon-left w-75" href="{{ url }}">{{ item.title }}</a></li>
              {% endfor %}
          </li>
          {% else %}
              {% if sub.roles is not defined %}
                  <li class="list-group-item text-center">
                    <div><a class="btn btn-primary btn-icon icon-left w-75" href="{{ sub.url| default(path(sub.path|default('app_home'))) }}"><i class="{{ sub.icon|default('fas fa-square') }}"></i> <span>{{ sub.title }}</span></a></div>
                  </li>
              {% else %}
                  {% if sub.roles|slice(0,1)=="!" and not is_granted(sub.roles|slice(1)) or is_granted(sub.roles) %}
                      <li class="list-group-item text-center">
                          <div><a class="btn btn-primary btn-icon icon-left w-75" href="{{ sub.url| default(path(sub.path|default('app_home'))) }}"><i class="{{ sub.icon|default('fas fa-square') }}"></i> <span>{{ sub.title }}</span></a></div>
                      </li>
                  {% endif %}
              {% endif %}
          {% endif %}
        {% endfor %}
        </ul>
      {% else %}
        <ul class="list-group  list-group-flush mb-3">
        <li class="list-group-item text-center {{ 'active'|is_active('^blank(.*)', page)|safe }}"><a class="btn btn-primary btn-icon icon-left w-75" href="{{ group.url| default(path(group.path|default('homepage'))) }}"><i class="{{ group.icon|default('far fa-square') }}"></i> <span> {{ group.title }}</span></a></li>
        </ul>
      {% endif %}
    </div></div>
    {% endfor %}

templates/table.html.twig
{% extends '@C3/_base.html.twig' %}

{% block plugins_css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <style>
        table.table {
            table-layout:fixed;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
{# 描画開始 #}
<section class="section">
    <div class="section-header">
        <h1>{% if block("title") is defined %}{{ block("title") }}{% endif %}</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="/">Top</a></div>
            <div class="breadcrumb-item"><a href="#">{% if block("title") is defined %}{{ block("title") }}{% endif %}</a></div>
            <div class="breadcrumb-item">All {% if block("title") is defined %}{{ block("title") }}{% endif %}</div>
        </div>
    </div>
    <div class="section-body">
        {% if block("description") is defined %}
        <h2 class="section-title">{{block('description')}}</h2>
        {% if block("description_contents") is defined %}
        <p class="section-lead">
            {{block('description_contents')}}
        </p>
        {% endif %}
        {% endif %}

        {# グループ検索用 データ準備 from repository #}
        {% if groups is not defined and repository is defined %}
            {% if is_method_exists(repository,'countByGroup') %}
                {% set groups=repository.countByGroup() %}
            {% endif %}
        {% endif %}
        {# グループ検索 描画開始 #}
        {% if repository is defined and is_method_exists(repository,'findByRequest') %}
        <div class="row">
            <div class="col-12">
                <div class="card mb-0">
                    <div class="card-body">
                        {% if groups is defined %}
                        {% set all_count=0 %}{% for cat in groups %}{% set all_count=all_count+cat.count %}{% endfor %}
                        <div class="float-left">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a class="nav-link{% if app.request.query.get('g') is null %} active{% endif %}" href="./">全て <span class="badge badge-{% if app.request.query.get('g') is not null %}primary{% else %}white{% endif %}">{{ all_count }}</span></a>
                            </li>
                            {% for cat in groups %}
                            <li class="nav-item">
                                <a class="nav-link{% if app.request.query.get('g') is not null%}{%  if app.request.query.get('g') == cat.name%} active{% endif %}{% endif %}" href="./?g={{ cat.name }}">{{ cat.name }} <span class="badge badge-{% if app.request.query.get('g')==cat.name%}white{% else %}primary{% endif %}">{{ cat.count }}</span></a>
                            </li>
                            {% endfor %}
                        </ul>
                        </div>
                        {% endif %}

                        <div class="float-right">
                            <form>
                                <div class="input-group">
                                    <input name="s" type="text" class="form-control" placeholder="Search" value="{{ app.request.query.get('s') }}">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {# グループ検索 描画終了 #}
        <div class="row mt-4">
            <div class="col-12">
                <div class="card card-statistic-1">
                    {% if block("page_icon") is defined %}
                        <div class="card-icon bg-primary">
                            <i class="{{ block("page_icon") }}"></i>
                        </div>
                    {% endif %}
                    {% if block("page_title") is defined %}
                    <div class="card-header">
                        {% if block('page_title') is defined %}
                            <h3>{{ block('page_title') }}</h3>
                        {% endif %}
                        {% if block('page_sub_title') is defined %}
                            <h4>{{ block('page_sub_title') }}</h4>
                        {% endif %}
                    </div>
                    {% endif %}
                    <div class="card-body">
                        <div class="table-responsive">
                            {{ block('body') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block page_js %}
<script>
    if (typeof jQuery !== 'undefined'){
        console.log("table.table Settings")
        $('table.table').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Japanese.json"
            },
            order: []
        });
    }
</script>
{% endblock %}